### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Syzyfek** [EmiNiemand/ImageLightRegression#1]
Thing To Do:

- [x] Resource Manager
- [x] Scene Objects Movement, Rotation And Scale
- [x] Gizmos
- [x] Post process showing selected object
- [x] Skybox
- [x] Showing rendered image and difference between loaded image and rendered image
- [x] Tool:
  - [x] GUI - imgui
  - [x] Drag and Drop
  - [x] Adding GameObjects and Components
  - [x] Changing values
  - [x] Starting application
  - [x] Scene saving and loading
- [x] Lights:
  - [x] Directional
  - [x] Spot
  - [x] Point
  - [x] Other (later)
- [x] Neural Network
- [x] Comparator
